# docker build . -t raspi/waqd:v1.5 -f ./test/testdata/auto_updater/dockerfile_install
FROM raspi/raspbian_py:1
USER pi
WORKDIR /home/pi
ENV COPY_PATH=/home/pi/waqd-dev
ENV DISPLAY=:99.0

# copy src
COPY --chown=pi ./src/ ${COPY_PATH}/src
COPY --chown=pi ./script/ ${COPY_PATH}/script/
COPY --chown=pi ./setup.py ${COPY_PATH}/
COPY --chown=pi ./MANIFEST.in ${COPY_PATH}/
COPY --chown=pi ./README.md ${COPY_PATH}/

RUN chmod +x ${COPY_PATH}/script/installer/start_installer.sh
RUN /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX \ 
    && ${COPY_PATH}/script/installer/start_installer.sh
# assertions
#RUN pipx --version
#RUN cat /home/pi/.local/pipx/venvs/waqd-1-6-0a6/lib/python3.7/site-packages/waqd/__init__.py

ENTRYPOINT bash
