FROM raspi/waqd_install:1
ARG WAQD_INSTALL_ROOT # you could give this a default value as well
ENV INSTALL_DIR=$WAQD_INSTALL_ROOT
# copy config
COPY ./src/config.ini ~/.waqd
# enable debug mode ?

# manipulate version number
RUN cat > $INSTALL_DIR/lib/python3.7/site-packages/waqd/__init__.py << EOF \
__version__ = "1.0.0" \
EOF
# start xserver
RUN /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX
RUN waqd-start

ENTRYPOINT bash
