# docker build . -t raspi/waqd:v1.5 -f ./test/testdata/auto_updater/dockerfile_install
FROM goszpeti/waqd:latest
USER pi
WORKDIR /home/pi
ENV COPY_PATH=/home/pi/waqd-dev
ENV DISPLAY=:99.0

# copy src
COPY --chown=pi ./src/ ${COPY_PATH}/src
COPY --chown=pi ./script/ ${COPY_PATH}/script/
COPY --chown=pi ./setup.py ${COPY_PATH}/
COPY --chown=pi ./MANIFEST.in ${COPY_PATH}/
COPY --chown=pi ./README.md ${COPY_PATH}/

RUN chmod +x ${COPY_PATH}/script/installer/start_installer.sh
RUN chmod +x ${COPY_PATH}/script/installer/exec_install.sh
# only works in bash
RUN bash -lic ". /home/pi/waqd-dev/script/installer/exec_install.sh && waqd_install"

ENTRYPOINT bash
