# Create with: docker build . -t goszpeti/raspi-base:latest -f ./test/testdata/auto_updater/dockerfile_base
FROM --platform=linux/arm64 devopskev/build-image-raspbian-bullseye-11-arm64-v8 AS base

ENV DISPLAY=:99.0
ENV DEBIAN_FRONTEND=noninteractive

RUN apt update --allow-releaseinfo-change
# RUN apt full-upgrade
# install virtual screen
RUN apt install xvfb libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0 -y
# install basics and the ui tools (these are huge)
RUN apt install libraspberrypi-bin libraspberrypi0 -y #raspi-config
RUN apt install policykit-1 hardlink ca-certificates curl -y
RUN apt install python3 python3-pip -y python3-venv -y
RUN apt install desktop-base policykit-1 gvfs obconf arandr -y

# LXDE
RUN /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX  &&  apt install lxde lxtask menu-xdg  xserver-xorg-video-fbdev xserver-xorg xinit xserver-xorg-video-fbturbo -y 
RUN apt install lightdm -y

RUN adduser --disabled-password --gecos '' pi 
RUN adduser pi sudo
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
RUN mkdir /etc/systemd/system/getty@tty1.service.d
RUN echo '[Service]\nExecStart=\nExecStart=-/sbin/agetty --autologin pi --noclear %I 38400 linux' >> /etc/systemd/system/getty@tty1.service.d/autologin.conf

VOLUME [ "/sys/fs/cgroup" ]

CMD ["/usr/sbin/init"]