# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Repos\weather_air_quality_device\src\waqd\ui\qt\qt\duration_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DurationDialog(object):
    def setupUi(self, DurationDialog):
        DurationDialog.setObjectName("DurationDialog")
        DurationDialog.resize(196, 217)
        DurationDialog.setModal(True)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(DurationDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(DurationDialog)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout.addWidget(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout.addWidget(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_4.setObjectName("radioButton_4")
        self.verticalLayout.addWidget(self.radioButton_4)
        self.radioButton_5 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_5.setObjectName("radioButton_5")
        self.verticalLayout.addWidget(self.radioButton_5)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.buttonBox = QtWidgets.QDialogButtonBox(DurationDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(DurationDialog)
        self.buttonBox.accepted.connect(DurationDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(DurationDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DurationDialog)

    def retranslateUi(self, DurationDialog):
        _translate = QtCore.QCoreApplication.translate
        DurationDialog.setWindowTitle(_translate("DurationDialog", "Display duration"))
        self.groupBox.setTitle(_translate("DurationDialog", "Display duration"))
        self.radioButton.setText(_translate("DurationDialog", "3 hours"))
        self.radioButton_2.setText(_translate("DurationDialog", "1 day"))
        self.radioButton_3.setText(_translate("DurationDialog", "3 days"))
        self.radioButton_4.setText(_translate("DurationDialog", "7 days"))
        self.radioButton_5.setText(_translate("DurationDialog", "30 days"))
