services:
  server:
    restart: always
    build:
      context: ../..
      dockerfile: src/waqd_website/Dockerfile
    image: waqd/waqd_website:latest
    container_name: waqd_website
    ports:
      - "80:8080"
    entrypoint: ["/bin/bash", "-c", ". /pdm-venv/bin/activate && uvicorn waqd_website.main:web_app --host 0.0.0.0 --port 8080"]
    # volumes:
    #   - ../..:/waqd