services:
  server:
    restart: always
    build:
      context: ../..
      dockerfile: src/waqd_website/Dockerfile
    image: waqd/waqd_website:latest
    container_name: waqd_website
    ports:
      - "80:8080"
