
### OpenMeteo ###
# 0 Clear sky
# 1, 2, 3	Mainly clear, partly cloudy, and overcast
# 45, 48	Fog and depositing rime fog
# 51, 53, 55	Drizzle: Light, moderate, and dense intensity
# 56, 57	Freezing Drizzle: Light and dense intensity
# 61, 63, 65	Rain: Slight, moderate and heavy intensity
# 66, 67	Freezing Rain: Light and heavy intensity
# 71, 73, 75	Snow fall: Slight, moderate, and heavy intensity
# 77	Snow grains
# 80, 81, 82	Rain showers: Slight, moderate, and violent
# 85, 86	Snow showers slight and heavy
# 95 * Thunderstorm: Slight or moderate
# 96, 99 * Thunderstorm with slight and heavy hail

om_day_code_to_ico = {
    0: "wi-day-sunny",  
    1: "wi-day-overcast",
    2: "wi-day-cloudy",
    3: "wi-cloudy",
    45: "wi-day-fog", 48: "wi-fog",
    51: "wi-day-sprinkle", 53: "wi-day-sleet", 55: "wi-day-sleet",
    56: "wi-day-rain-mix", 57: "wi-day-rain-mix",
    61: "wi-day-rain", 63: "wi-day-rain", 65: "wi-day-rain",
    66: "wi-day-rain-mix", 67: "wi-day-rain-mix",  # TODO
    71: "wi-day-snow", 73: "wi-day-snow", 75: "wi-day-snow",
    77: "wi-day-snow",
    80: "wi-day-showers", 81: "wi-day-showers", 82: "wi-day-showers",
    85: "wi-day-snow", 86: "wi-day-snow",
    95: "wi-day-thunderstorm",
    96: "wi-day-hail", 99: "wi-day-hail"  # TODO hail
}
om_night_code_to_ico = {
    0: "wi-night-clear",
    1: "wi-night-alt-partly-cloudy",
    2: "wi-night-alt-cloudy",
    3: "wi-night-alt-cloudy",
    45: "wi-night-fog", 48: "wi-fog",
    51: "wi-night-alt-sprinkle", 53: "wi-night-alt-sleet", 55: "wi-night-alt-sleet",
    56: "wi-night-alt-rain-mix", 57: "wi-night-alt-rain-mix",
    61: "wi-night-alt-rain", 63: "wi-night-alt-rain", 65: "wi-night-alt-rain",
    66: "wi-night-alt-rain-mix", 67: "wi-day-rain-mix",  # TODO
    71: "wi-night-alt-snow", 73: "wi-night-alt-snow", 75: "wi-night-alt-snow",
    77: "wi-night-alt-snow",
    80: "wi-night-alt-showers", 81: "wi-night-alt-showers", 82: "wi-day-showers",
    85: "wi-night-alt-snow", 86: "wi-night-alt-snow",
    95: "wi-night-alt-thunderstorm",
    96: "wi-night-alt-snow-thunderstorm", 99: "wi-night-alt-snow-thunderstorm"  # TODO hail
}
om_condition_map = {  # for bg image - TODO use WeatherQuality
    0: "clear",  # add table for this
    1: "clouds", 2: "clouds", 3: "clouds",
    45: "fog", 48: "fog",
    51: "drizzle", 53: "drizzle", 55: "drizzle",
    56: "drizzle", 57: "drizzle",  # TODO get image
    61: "rain", 63: "rain", 65: "rain",
    66: "rain", 67: "rain",  # TODO
    71: "snow", 73: "snow", 75: "snow",
    77: "snow",
    80: "rain", 81: "rain", 82: "rain",  # TODO showers
    85: "snow", 86: "snow",
    95: "thunderstorm",
    96: "thunderstorm", 99: "thunderstorm"  # TODO hail
}

### OpenWeatherMap ### 

owm_icon_mapping = {
    "day-200": "wi-day-thunderstorm",
    "day-201": "wi-day-thunderstorm",
    "day-202": "wi-day-thunderstorm",
    "day-210": "wi-day-lightning",
    "day-211": "wi-day-lightning",
    "day-212": "wi-day-lightning",
    "day-221": "wi-day-lightning",
    "day-230": "wi-day-thunderstorm",
    "day-231": "wi-day-thunderstorm",
    "day-232": "wi-day-thunderstorm",
    "day-300": "wi-day-sprinkle",
    "day-301": "wi-day-sprinkle",
    "day-302": "wi-day-rain",
    "day-310": "wi-day-rain",
    "day-311": "wi-day-rain",
    "day-312": "wi-day-rain",
    "day-313": "wi-day-rain",
    "day-314": "wi-day-rain",
    "day-321": "wi-day-sprinkle",
    "day-500": "wi-day-sprinkle",
    "day-501": "wi-day-rain",
    "day-502": "wi-day-rain",
    "day-503": "wi-day-rain",
    "day-504": "wi-day-rain",
    "day-511": "wi-day-rain-mix",
    "day-520": "wi-day-showers",
    "day-521": "wi-day-showers",
    "day-522": "wi-day-showers",
    "day-531": "wi-day-storm-showers",
    "day-600": "wi-day-snow",
    "day-601": "wi-day-sleet",
    "day-602": "wi-day-snow",
    "day-611": "wi-day-rain-mix",
    "day-612": "wi-day-rain-mix",
    "day-615": "wi-day-rain-mix",
    "day-616": "wi-day-rain-mix",
    "day-620": "wi-day-rain-mix",
    "day-621": "wi-day-snow",
    "day-622": "wi-day-snow",
    "day-701": "wi-day-showers",
    "day-711": "wi-smoke",
    "day-721": "wi-day-haze",
    "day-731": "wi-dust",
    "day-741": "wi-day-fog",
    "day-761": "wi-dust",
    "day-762": "wi-dust",
    "day-781": "wi-tornado",
    "day-800": "wi-day-sunny",
    "day-801": "wi-day-sunny-overcast",
    "day-802": "wi-day-cloudy",
    "day-803": "wi-day-cloudy",
    "day-804": "wi-cloudy",
    "day-900": "wi-tornado",
    "day-902": "wi-hurricane",
    "day-903": "wi-snowflake-cold",
    "day-904": "wi-hot",
    "day-906": "wi-day-hail",
    "day-957": "wi-strong-wind",
    "night-200": "wi-night-alt-thunderstorm",
    "night-201": "wi-night-alt-thunderstorm",
    "night-202": "wi-night-alt-thunderstorm",
    "night-210": "wi-night-alt-lightning",
    "night-211": "wi-night-alt-lightning",
    "night-212": "wi-night-alt-lightning",
    "night-221": "wi-night-alt-lightning",
    "night-230": "wi-night-alt-thunderstorm",
    "night-231": "wi-night-alt-thunderstorm",
    "night-232": "wi-night-alt-thunderstorm",
    "night-300": "wi-night-alt-sprinkle",
    "night-301": "wi-night-alt-sprinkle",
    "night-302": "wi-night-alt-rain",
    "night-310": "wi-night-alt-rain",
    "night-311": "wi-night-alt-rain",
    "night-312": "wi-night-alt-rain",
    "night-313": "wi-night-alt-rain",
    "night-314": "wi-night-alt-rain",
    "night-321": "wi-night-alt-sprinkle",
    "night-500": "wi-night-alt-sprinkle",
    "night-501": "wi-night-alt-rain",
    "night-502": "wi-night-alt-rain",
    "night-503": "wi-night-alt-rain",
    "night-504": "wi-night-alt-rain",
    "night-511": "wi-night-alt-rain-mix",
    "night-520": "wi-night-alt-showers",
    "night-521": "wi-night-alt-showers",
    "night-522": "wi-night-alt-showers",
    "night-531": "wi-night-alt-storm-showers",
    "night-600": "wi-night-alt-snow",
    "night-601": "wi-night-alt-sleet",
    "night-602": "wi-night-alt-snow",
    "night-611": "wi-night-alt-rain-mix",
    "night-612": "wi-night-alt-rain-mix",
    "night-615": "wi-night-alt-rain-mix",
    "night-616": "wi-night-alt-rain-mix",
    "night-620": "wi-night-alt-rain-mix",
    "night-621": "wi-night-alt-snow",
    "night-622": "wi-night-alt-snow",
    "night-701": "wi-night-alt-showers",
    "night-711": "wi-smoke",
    "night-721": "wi-day-haze",
    "night-731": "wi-dust",
    "night-741": "wi-night-fog",
    "night-761": "wi-dust",
    "night-762": "wi- ",
    "night-781": "wi-tornado",
    "night-800": "wi-night-clear",
    "night-801": "wi-night-alt-partly-cloudy",
    "night-802": "wi-night-alt-cloudy",
    "night-803": "wi-night-alt-cloudy",
    "night-804": "wi-cloudy",
    "night-900": "wi-tornado",
    "night-902": "wi-hurricane",
    "night-903": "wi-snowflake-cold",
    "night-904": "wi-hot",
    "night-906": "wi-night-alt-hail",
    "night-957": "wi-strong-wind",
    "day-windy": "wi-day-windy",
    "day-cloudy-windy": "wi-cloudy-windy",
    "day-rain-windy": "wi-day-rain-wind",
    "day-snow-windy": "wi-day-snow-wind",
    "night-windy": "wi-windy",
    "night-cloudy-windy": "wi-night-alt-cloudy-windy",
    "night-rain-windy": "wi-night-alt-rain-wind",
    "night-snow-windy": "wi-night-alt-snow-wind",
    "N/A": "wi-na"
}
