name: Build waqd_website Docker Image

on:
  push:
    branches: [master]
    paths:
      - 'src/waqd_website/**'
  pull_request:
    branches: [master]
    paths:
      - 'src/waqd_website/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ARM64
    outputs:
      new_tag: ${{ steps.build_step.outputs.new_tag }}  # Define output for the job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        id: build_step  # Add ID to reference this step
        run: |
          NEW_TAG=$(git rev-parse --short HEAD)
          echo "new_tag=${NEW_TAG}" >> $GITHUB_OUTPUT
          docker buildx build \
            --platform linux/arm64/v8 \
            --build-arg BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
            --build-arg VCS_REF=$(git rev-parse HEAD) \
            --build-arg VERSION=$(git describe --tags) \
            -t goszpeti/waqd_website:${NEW_TAG} \
            -f src/waqd_website/Dockerfile \
            .

      - name: Push Docker image
        run: |
          echo ${{ secrets.DOCKER_ACCESS_TOKEN }} | docker login -u goszpeti --password-stdin
          docker push goszpeti/waqd_website:${{ steps.build_step.outputs.new_tag }}

  update-image-tag:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          repository: 'WAQD/waqd_infrastructure'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update image tag in docker-compose.yml
        run: |
          IMAGE_NAME="waqd_website"
          sed -i "s|$IMAGE_NAME:[^ ]*|$IMAGE_NAME:${{ needs.build.outputs.new_tag }}|g" deployment/waqd-website.yaml

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docker-compose.yml
          git commit -m "Update image tag to ${{ needs.build.outputs.new_tag }}" || echo "No changes to commit"
          git push
